// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenFreeSchools.Data;

#nullable disable

namespace OpenFreeSchools.Data.Migrations
{
    [DbContext(typeof(OpenFreeSchoolsDbContext))]
    [Migration("20230725130023_update-db-model")]
    partial class updatedbmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpenFreeSchools.Data.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TimeOfChange")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog");

                    b.ToTable("AuditLog", "concerns", t =>
                        {
                            t.HasTrigger("AuditLog_Trigger");
                        });
                });

            modelBuilder.Entity("OpenFreeSchools.Data.Models.Projects.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentFreeSchoolName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project Status.Current free school name");

                    b.Property<string>("FreeSchoolApplicationWave")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project Status.Free school application wave");

                    b.Property<string>("FreeSchoolsApplicationNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Project Status.Free schools application number");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Projects", "openFreeSchool", t =>
                        {
                            t.HasTrigger("Projects_Trigger");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
